# -*- coding: utf-8 -*-
"""mimii_transformer

Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/1xH_z0QgVp_LgGw1ODr_3nnblnyjVzFHB
"""

# --- 1. データのダウンロードと解凍 (自動上書きオプション付き) ---
# データのダウンロード（約1.3GBあるため少し時間がかかります）
!wget https://zenodo.org/record/3384388/files/-6_dB_valve.zip
!unzip -qo ./-6_dB_valve.zip -d mimii_valve

# --- 2. 音声データの可視化 ---
import librosa
import librosa.display
import matplotlib.pyplot as plt
import numpy as np

# 正常音と異常音のファイルパス（適当なサンプルのパスを指定）
normal_path = 'mimii_valve/valve/id_00/normal/00000000.wav'
abnormal_path = 'mimii_valve/valve/id_00/abnormal/00000000.wav'

def plot_audio_features(file_path, title_prefix):
    # 1. 音声データの読み込み
    y, sr = librosa.load(file_path, sr=None)

    plt.figure(figsize=(12, 8))

    # 2. 波形 (Waveform) のプロット
    plt.subplot(2, 1, 1)
    librosa.display.waveshow(y, sr=sr, alpha=0.8)
    plt.title(f'{title_prefix} - Waveform')
    plt.xlabel('Time (s)')
    plt.ylabel('Amplitude')

    # 3. メルスペクトログラムの計算とプロット
    mel_spect = librosa.feature.melspectrogram(y=y, sr=sr, n_fft=2048, hop_length=512, n_mels=128)
    mel_spect_db = librosa.power_to_db(mel_spect, ref=np.max)

    plt.subplot(2, 1, 2)
    librosa.display.specshow(mel_spect_db, sr=sr, x_axis='time', y_axis='mel')
    plt.colorbar(format='%+2.0f dB')
    plt.title(f'{title_prefix} - Mel Spectrogram')

    plt.tight_layout()
    plt.show()

# 正常音・異常音の可視化実行
plot_audio_features(normal_path, "Normal Valve")
plot_audio_features(abnormal_path, "Abnormal Valve")

# --- 3. PyTorch Dataset & DataLoader の定義 (id_00を学習用に使用) ---
import os
import glob
import torch
from torch.utils.data import Dataset, DataLoader

class MIMIIDataset(Dataset):
    def __init__(self, data_dir, machine_type='valve', transform=None):
        self.transform = transform

        # 初期プロトタイプとして id_00 のデータセットをベースラインとして収集
        normal_dir = os.path.join(data_dir, machine_type, 'id_00', 'normal', '*.wav')
        abnormal_dir = os.path.join(data_dir, machine_type, 'id_00', 'abnormal', '*.wav')

        self.normal_files = glob.glob(normal_dir)
        self.abnormal_files = glob.glob(abnormal_dir)
        self.all_files = self.normal_files + self.abnormal_files

        # ラベル付け：正常を0、異常を1とする
        self.labels = [0] * len(self.normal_files) + [1] * len(self.abnormal_files)

    def __len__(self):
        return len(self.all_files)

    def __getitem__(self, idx):
        file_path = self.all_files[idx]
        label = self.labels[idx]

        y, sr = librosa.load(file_path, sr=16000)
        mel_spect = librosa.feature.melspectrogram(y=y, sr=sr, n_fft=1024, hop_length=512, n_mels=128)
        log_mel_spectrogram = librosa.power_to_db(mel_spect, ref=np.max)
        
        # 改善施策：Min-Max正規化を適用し特徴量のスケールを統一
        log_mel_spectrogram = (log_mel_spectrogram - log_mel_spectrogram.min()) / (log_mel_spectrogram.max() - log_mel_spectrogram.min() + 1e-6)

        feature_tensor = torch.tensor(log_mel_spectrogram, dtype=torch.float32).unsqueeze(0)
        label_tensor = torch.tensor(label, dtype=torch.long)

        return feature_tensor, label_tensor

# データセットとデータローダーの作成
dataset = MIMIIDataset(data_dir='mimii_valve')
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

# --- 4. Vision Transformer (AudioViT) モデルの定義 ---
!pip install -q timm
import torch.nn as nn
import torch.nn.functional as F
import timm

class AudioViT(nn.Module):
    def __init__(self, num_classes=2):
        super().__init__()
        # 1チャンネル入力(モノラル)に対応した事前学習済みViT-Tiny
        self.vit = timm.create_model('vit_tiny_patch16_224', pretrained=True, in_chans=1, num_classes=num_classes)

    def forward(self, x):
        # 任意の時間幅のスペクトログラムをViTの要求サイズ (224, 224) に動的リサイズ
        x = F.interpolate(x, size=(224, 224), mode='bilinear', align_corners=False)
        return self.vit(x)

model = AudioViT(num_classes=2)

# --- 5. Weights & Biases (W&B) による実験管理と学習実行 ---
import wandb
import torch.optim as optim
from tqdm import tqdm

# W&Bへのログイン（※ご自身のAPIキーに書き換えてください）
wandb.login(key="YOUR_WANDB_API_KEY")

# W&Bプロジェクトの初期化
wandb.init(
    project="factory-anomaly-detection",
    name="vit-tiny-baseline",
    config={
        "learning_rate": 1e-4,
        "architecture": "ViT-Tiny",
        "dataset": "MIMII Valve",
        "epochs": 3,
        "batch_size": 32
    }
)

criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=wandb.config.config["learning_rate"])

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

epochs = wandb.config.epochs

print("🚀 提案手法（ViT-Tiny）の学習をスタートします...")
for epoch in range(epochs):
    model.train()
    running_loss = 0.0

    for features, labels in tqdm(dataloader, desc=f"Epoch {epoch+1}/{epochs}"):
        features, labels = features.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(features)
        loss = criterion(outputs, labels)

        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        wandb.log({"batch_loss": loss.item()})

    avg_loss = running_loss / len(dataloader)
    wandb.log({"epoch": epoch + 1, "epoch_loss": avg_loss})
    print(f"Epoch {epoch+1} - Average Loss: {avg_loss:.4f}")

wandb.finish()
print("🎉 学習とW&Bへの記録が完了しました！")

# 推論エンドポイント(app.py)との高い互換性を担保するため、接頭辞なしの純粋なViT重みとして保存
torch.save(model.vit.state_dict(), 'vit_anomaly_detection.pth')
print("✅ モデルの保存が完了しました！（vit_anomaly_detection.pth）")

# --- 6. マルチマシン（id_00, 02, 04, 06）から未知の評価用データを隔離抽出 ---
import random
import shutil
from google.colab import files

BASE_DIR = '/content/mimii_valve/valve'
IDS = ['id_00', 'id_02', 'id_04', 'id_06']
OUTPUT_DIR = '/content/test_samples_all'

if os.path.exists(OUTPUT_DIR):
    shutil.rmtree(OUTPUT_DIR)
os.makedirs(f'{OUTPUT_DIR}/normal', exist_ok=True)
os.makedirs(f'{OUTPUT_DIR}/abnormal', exist_ok=True)

all_normal_files = []
all_abnormal_files = []

for machine_id in IDS:
    normal_dir = os.path.join(BASE_DIR, machine_id, 'normal')
    abnormal_dir = os.path.join(BASE_DIR, machine_id, 'abnormal')
    
    if os.path.exists(normal_dir):
        for f in os.listdir(normal_dir):
            if f.endswith('.wav'):
                all_normal_files.append((machine_id, os.path.join(normal_dir, f), f))
    if os.path.exists(abnormal_dir):
        for f in os.listdir(abnormal_dir):
            if f.endswith('.wav'):
                all_abnormal_files.append((machine_id, os.path.join(abnormal_dir, f), f))

# 評価用の数を指定（正常100、異常150）
random.seed(42)
sampled_normal = random.sample(all_normal_files, min(100, len(all_normal_files)))
sampled_abnormal = random.sample(all_abnormal_files, min(150, len(all_abnormal_files)))

# ファイル名被りを防ぐため、IDを接頭辞に付与してコピー
for machine_id, src_path, filename in sampled_normal:
    shutil.copy(src_path, os.path.join(OUTPUT_DIR, 'normal', f"{machine_id}_{filename}"))
for machine_id, src_path, filename in sampled_abnormal:
    shutil.copy(src_path, os.path.join(OUTPUT_DIR, 'abnormal', f"{machine_id}_{filename}"))

print(f"✅ テストデータの隔離が完了: 正常={len(sampled_normal)}個, 異常={len(sampled_abnormal)}個")

# --- 7. 対戦相手（CNN/ResNet18）の高速学習と、多角的指標によるベンチマーク評価 ---
from sklearn.metrics import accuracy_score, recall_score, f1_score, roc_auc_score

# 隔離セットのパスを特定
test_normal_paths = [os.path.join(OUTPUT_DIR, 'normal', f"{m}_{fn}") for m, _, fn in sampled_normal]
test_abnormal_paths = [os.path.join(OUTPUT_DIR, 'abnormal', f"{m}_{fn}") for m, _, fn in sampled_abnormal]
test_set_flat = [(p, 0) for p in test_normal_paths] + [(p, 1) for p in test_abnormal_paths]

# 公平性の担保：テストデータ以外の残存データでCNNを3エポック学習
test_normal_originals = set([src for _, src, _ in sampled_normal])
test_abnormal_originals = set([src for _, src, _ in sampled_abnormal])

train_files_for_cnn = []
for m_id, src, _ in all_normal_files:
    if src not in test_normal_originals: train_files_for_cnn.append((src, 0))
for m_id, src, _ in all_abnormal_files:
    if src not in test_abnormal_originals: train_files_for_cnn.append((src, 1))

class CNNTrainDataset(Dataset):
    def __init__(self, file_pairs):
        self.file_pairs = file_pairs
    def __len__(self): return len(self.file_pairs)
    def __getitem__(self, idx):
        f_path, lbl = self.file_pairs[idx]
        y, sr = librosa.load(f_path, sr=16000)
        mel = librosa.feature.melspectrogram(y=y, sr=sr, n_fft=1024, hop_length=512, n_mels=128)
        log_mel = librosa.power_to_db(mel, ref=np.max)
        log_mel = (log_mel - log_mel.min()) / (log_mel.max() - log_mel.min() + 1e-6)
        tensor = torch.tensor(log_mel, dtype=torch.float32).unsqueeze(0)
        return F.interpolate(tensor.unsqueeze(0), size=(224, 224), mode='bilinear', align_corners=False).squeeze(0), lbl

cnn_train_loader = DataLoader(CNNTrainDataset(train_files_for_cnn), batch_size=32, shuffle=True, drop_last=True)

print("\n🏋️ 対照実験：ベースラインCNN (ResNet18) の3エポック学習を開始します...")
cnn_model = timm.create_model('resnet18', pretrained=False, num_classes=2, in_chans=1).to(device)
cnn_optimizer = optim.AdamW(cnn_model.parameters(), lr=1e-4)

cnn_model.train()
for epoch in range(3):
    for inputs, labels in tqdm(cnn_train_loader, desc=f"CNN Epoch {epoch+1}/3"):
        inputs, labels = inputs.to(device), labels.to(device)
        cnn_optimizer.zero_grad()
        loss = criterion(cnn_model(inputs), labels)
        loss.backward()
        cnn_optimizer.step()

# 両モデルの一括多角的指標評価（前処理関数）
def eval_preprocess(file_path):
    y, sr = librosa.load(file_path, sr=16000)
    mel = librosa.feature.melspectrogram(y=y, sr=sr, n_fft=1024, hop_length=512, n_mels=128)
    log_mel = librosa.power_to_db(mel, ref=np.max)
    log_mel = (log_mel - log_mel.min()) / (log_mel.max() - log_mel.min() + 1e-6)
    tensor = torch.tensor(log_mel, dtype=torch.float32).unsqueeze(0).unsqueeze(0)
    return F.interpolate(tensor, size=(224, 224), mode='bilinear', align_corners=False).to(device)

# 評価用ViT（保存した単体ウェイトからロード）
vit_eval_model = timm.create_model('vit_tiny_patch16_224', pretrained=False, num_classes=2, in_chans=1).to(device)
vit_eval_model.load_state_dict(torch.load('vit_anomaly_detection.pth', map_location=device))

models_to_compare = {'Vision Transformer (Proposed)': vit_eval_model.eval(), 'ResNet18 (Baseline CNN)': cnn_model.eval()}
benchmarks = {}

print("\n🚀 隔離テストデータ250件に対する多角的指標評価（Accuracy, Recall, F1, ROC-AUC）を実行中...")
for m_name, tgt_model in models_to_compare.items():
    y_true, y_pred, y_scores = [], [], []
    for f_path, label in test_set_flat:
        try:
            tensor = eval_preprocess(f_path)
            with torch.no_grad():
                probs = F.softmax(tgt_model(tensor), dim=1)
                pred = torch.argmax(probs, dim=1).item()
                prob_abnormal = probs[0][1].item()
            y_true.append(label)
            y_pred.append(pred)
            y_scores.append(prob_abnormal)
        except: pass
    benchmarks[m_name] = {
        'Acc': accuracy_score(y_true, y_pred) * 100,
        'Rec': recall_score(y_true, y_pred) * 100,
        'F1': f1_score(y_true, y_pred),
        'AUC': roc_auc_score(y_true, y_scores)
    }

print("\n" + "="*75)
print("🏆 READMEにそのまま記載可能なベンチマーク統計")
print("="*75)
for m_name, metrics in benchmarks.items():
    print(f"■ {m_name}")
    print(f"  - Accuracy (総合精度) : {metrics['Acc']:.1f}%")
    print(f"  - Recall (異常検知率)   : {metrics['Rec']:.1f}%  <-- 現場の最重要指標")
    print(f"  - F1-Score (調和平均)   : {metrics['F1']:.3f}")
    print(f"  - ROC-AUC (識別能力値)  : {metrics['AUC']:.3f}")
    print("-"*75)

# --- 8. 成果物テストデータのZIP化とColabダウンロード ---
print("📦 テストデータをZIPファイルに圧縮しています...")
shutil.make_archive('/content/test_samples_all', 'zip', OUTPUT_DIR)

print("⬇️ ローカルへのダウンロードを開始します...")
files.download('/content/test_samples_all.zip')